#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=16
stage=-1
stop_stage=100

vocab_sizes=(
  1000
  # 500
)

# Split L subset to this number of pieces
# This is to avoid OOM during feature extraction.
num_splits=1000

dl_dir=$PWD/download
splits_dir=$PWD/splits_dir

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"


if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  if [ ! -d $dl_dir/GigaSpeech ]; then
    ./local/download_gigaspeech.py --config xl --output_dir $dl_dir
    ./local/download_gigaspeech.py --config test --output_dir $dl_dir
    ./local/download_gigaspeech.py --config dev --output_dir $dl_dir
  fi

  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi

  if [ ! -d $dl_dir/audio_splits ]; then
    lhotse download hallway $dl_dir
  fi

  if [ ! -d $dl_dir/bookbot_en_v1-v2 ]; then
    lhotse download bookbot-huggingface bookbot/bookbot_en_v1-v2 $dl_dir text ""
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare manifests"
  mkdir -p data/manifests

  lhotse prepare bookbot-huggingface $dl_dir/GigaSpeech data/manifests
  lhotse prepare bookbot-huggingface $dl_dir/bookbot_en_v1-v2 data/manifests --normalize-words=true
  lhotse prepare musan $dl_dir/musan data/manifests
  lhotse prepare hallway $dl_dir/audio_splits data/manifests
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Preprocess GigaSpeech manifest"
  if [ ! -f data/fbank/.gigaspeech_preprocess.done ]; then
    ./local/preprocess_gigaspeech.py
    touch data/fbank/.gigaspeech_preprocess.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute fbanks"
  mkdir -p data/fbank

  ./local/compute_fbank_gigaspeech.py
  ./local/compute_fbank_musan.py
  ./local/compute_fbank_hallway.py
  ./local/compute_fbank_bookbot.py
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Split L subset into ${num_splits} pieces"
  split_dir=data/fbank/GigaSpeech_train_split_${num_splits}
  if [ ! -f $split_dir/.gigaspeech_train_split.done ]; then
    lhotse split $num_splits ./data/fbank/GigaSpeech_cuts_train_raw.jsonl.gz $split_dir
    touch $split_dir/.gigaspeech_train_split.done
  fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Compute features for L"
  # Note: The script supports --start and --stop options.
  # You can use several machines to compute the features in parallel.
  if [ ! -f data/fbank/.gigaspeech_train.done ]; then
    ./local/compute_fbank_gigaspeech_splits.py \
      --num-workers $nj \
      --batch-duration 600 \
      --num-splits $num_splits
    touch data/fbank/.gigaspeech_train.done
  fi
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  log "Stage 6: Combine features for L (may take 15 hours)"
  if [ ! -f data/fbank/GigaSpeech_cuts_train.jsonl.gz ]; then
    pieces=$(find data/fbank/GigaSpeech_train_split_${num_splits} -name "GigaSpeech_cuts_train.*.jsonl.gz")
    lhotse combine $pieces data/fbank/GigaSpeech_cuts_train.jsonl.gz
  fi
fi

if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
  log "Stage 7: Prepare BPE train data and set of words"
  lang_dir=data/lang
  mkdir -p $lang_dir

  if [ ! -f $lang_dir/train.txt ]; then
    ./local/prepare_transcripts.py \
      --manifests-dir data/manifests \
      --output-text-path $lang_dir/train.txt
  fi

  if [ ! -f $lang_dir/words.txt ]; then
    ./local/prepare_words.py \
      --manifests-dir data/manifests \
      --lang-dir $lang_dir
  fi
fi

if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
  log "Stage 8: Prepare BPE based lang"

  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=data/lang_bpe_${vocab_size}
    mkdir -p $lang_dir
    cp data/lang/words.txt $lang_dir

    ./local/train_bpe_model.py \
      --lang-dir $lang_dir \
      --vocab-size $vocab_size \
      --transcript data/lang/train.txt

    if [ ! -f $lang_dir/L_disambig.pt ]; then
      ./local/prepare_lang_bpe.py --lang-dir $lang_dir --oov "<unk>"
    fi
  done
fi